# Generated by Django 4.1.1 on 2022-10-19 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('zipcode', models.CharField(max_length=20)),
                ('rooms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('baths', models.DecimalField(decimal_places=1, max_digits=4)),
                ('size', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='ListingFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_2d', models.ImageField(upload_to='photos/floor2d')),
                ('floor_3d', models.ImageField(upload_to='photos/floo3rd')),
            ],
        ),
        migrations.CreateModel(
            name='ListingAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.amenity')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
