# Generated by Django 4.1.1 on 2022-12-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_baths_remove_listing_half_baths_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
    ]
