# Generated by Django 4.1.1 on 2022-12-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('listings', '0006_remove_listingimages_url_remove_listingvideo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listingimages',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listingvideo',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listingvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='listing',
            name='floor_plan',
            field=models.ManyToManyField(related_name='floor_plan', to='uploader.dropbox'),
        ),
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ManyToManyField(related_name='images', to='uploader.dropbox'),
        ),
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.ManyToManyField(related_name='video', to='uploader.dropbox'),
        ),
        migrations.DeleteModel(
            name='ListingFloorPlan',
        ),
        migrations.DeleteModel(
            name='ListingImages',
        ),
        migrations.DeleteModel(
            name='ListingVideo',
        ),
    ]
