# Generated by Django 4.1.1 on 2023-01-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_categorydetails_categoryamenities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydetails',
            old_name='amenity',
            new_name='detail',
        ),
    ]
