# Generated by Django 4.1.1 on 2023-02-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_listing_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmap',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='listingmap',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
