# Generated by Django 4.1.1 on 2023-02-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_listingmap_lat_alter_listingmap_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='listingcharacteristics',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
