# Generated by Django 4.1.1 on 2023-02-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcharacteristics',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
