# Generated by Django 4.1.1 on 2023-02-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_alter_listingcharacteristics_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcharacteristics',
            name='balcony',
            field=models.IntegerField(default=0),
        ),
    ]
