# Generated by Django 4.1.1 on 2023-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_listingcharacteristics_additional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='categoryamenities',
            options={'verbose_name_plural': 'Category Amenities'},
        ),
        migrations.AlterModelOptions(
            name='categorydetails',
            options={'verbose_name_plural': 'Category Details'},
        ),
        migrations.AlterModelOptions(
            name='listingamenities',
            options={'verbose_name_plural': 'Listing Amenities'},
        ),
        migrations.AlterModelOptions(
            name='listingdetails',
            options={'verbose_name_plural': 'Listing Details'},
        ),
        migrations.AlterModelOptions(
            name='listingfavorites',
            options={'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='listingmap',
            options={'verbose_name_plural': 'Listing Map'},
        ),
        migrations.AlterField(
            model_name='listingmap',
            name='zoom',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
