# Generated by Django 4.1.1 on 2023-02-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_amenity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Serbia', max_length=150)),
                ('city', models.CharField(default=None, max_length=150)),
                ('municipality', models.CharField(default=None, max_length=250)),
                ('area', models.CharField(default=None, max_length=250)),
            ],
        ),
    ]
