# Generated by Django 4.1.1 on 2023-03-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_remove_listing_price_listingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='virtual_tour',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='video',
        ),
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
