# Generated by Django 4.1.1 on 2023-03-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_listing_virtual_tour_remove_listing_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[(0, 'Prodaja'), (1, 'Izdavanje')], default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[(0, 'Aktivan'), (1, 'Na čekanju'), (2, 'Istekao')], default=1, max_length=25),
        ),
    ]
