# Generated by Django 4.1.1 on 2023-03-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_listing_type_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcharacteristics',
            name='set_up',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
