# Generated by Django 4.1.1 on 2023-04-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_listingcharacteristics_set_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Popular Locations',
                'ordering': ['order'],
            },
        ),
    ]
