# Generated by Django 4.1.1 on 2023-04-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_dropbox_file'),
        ('listings', '0027_popularlocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularlocations',
            name='image',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='uploader.dropbox'),
        ),
    ]
