# Generated by Django 4.1.1 on 2022-12-24 09:26

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropBox',
            fields=[
                ('id', models.CharField(db_index=True, default=uploader.models.generate_random_code, max_length=16, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Drop Boxes',
            },
        ),
    ]
