# Generated by Django 4.1.1 on 2023-03-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropbox',
            name='file',
            field=models.FileField(upload_to='listings'),
        ),
    ]
