# Generated by Django 4.1.1 on 2023-03-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='tax_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
