# Generated by Django 4.1.1 on 2023-03-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_identification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
