# Generated by Django 4.1.1 on 2023-03-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_category_article_cover_article_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('Blog', 'Blog'), ('News', 'News')], default='Blog', max_length=4),
        ),
    ]
