# Generated by Django 4.1.1 on 2023-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_articlecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='for_article_type',
            field=models.CharField(choices=[('Blog', 'Blog'), ('News', 'News')], default='Blog', max_length=4),
        ),
    ]
